# Database (Dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/hs_iphones
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.show-sql=true

# JWT
jwt.secret=hs-iphones-dev-secret-key-deve-ter-pelo-menos-256-bits-ok
jwt.expiration=86400000
