ALTER TABLE client ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE supplier ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE product ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
